services:
  - type: web
    name: resume_screener
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resume_screener.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resume_screener.settings
      - key: PYTHON_VERSION
        value: 3.10
